# This workflow Print on Screen the Context Variables

name: Variables Contexto

on:
  workflow_dispatch:

jobs:
  coptexto:
    strategy:
      matrix:
        version: [1.0.1, 2.0.1]
        variable: "context variable"
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar Variables Contexto
        run:
            echo "Variables de contexto:" &&
            echo "matrix.variable" &&
            echo ${{matrix.variable}} &&